In [45]:
import numpy as np

# 일반 리스트와 numpy 리스트와 비교
num1 = [1, 2, 3, 4]
num1

num2 = [5, 6, 7, 8]
num2
print(num1 + num2)

# 넘파이로 리스트를 생성
x = np.array([1, 2, 3, 4])
print(x)
print(type(x))
print(x.shape)  #(1, 4) -> (4, )
print(x.dtype)

[1, 2, 3, 4, 5, 6, 7, 8]
[1 2 3 4]
<class 'numpy.ndarray'>
(4,)
int32


In [47]:
# numpy 연산
# 1차원 리스트에서는 원소의 개수가 다르면 오류 발생
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])

print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x.dtype)

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]
float64


In [27]:
# numpy는 한 가지 자료형만 허용
a = np.array([1, 2, 'a', 'b'])
print(a)

# 일반 리스트 - 여러가지 자료형 허용
cart = ['생수', '감자', 100, True]
print(cart)

['1' '2' 'a' 'b']
['생수', '감자', 100, True]


In [39]:
# 넘파이 이차원 리스트
# 내부 리스트의 원소의 개수가 같아야 함 - 오류 발생
a = np.array([[1,2], [3, 4]])
print(a)
print(b.shape)

b = np.array([[1,2], [3]])
print(b)

[[1 2]
 [3 4]]
(2, 2)


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [53]:
# zeros() - 리스트의 모든 원소를 0으로 설정
# ones() - - 리스트의 모든 원소를 1로 설정
a1 = np.zeros((3, 3))
print(a1)
print(a1.shape)

a2 = np.ones((2, 3))
print(a2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)
[[1. 1. 1.]
 [1. 1. 1.]]


In [67]:
# np.arange()

import numpy as np

print(range(10))
print(list(range(10)))

a = np.arange(10) + 1
print(a)

a2 = np.arange(3, 9)
print(a2)

a3 = np.arange(3, 9, 2)
print(a3)

range(0, 10)
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 1  2  3  4  5  6  7  8  9 10]
[3 4 5 6 7 8]
[3 5 7]
